#!/usr/bin/env python3
# Generate tranche_dirs.tsv: ZINC-22 ids and the 3D-database directory each belongs in, produced by
# running the ZINC maintainers' own code at pinned commits — their id encoder (cartblanche22 encode.py)
# and their directory function (zinc22-3d generate/build_ligands.py get_zinc_directory_hash). Nothing
# here re-implements either: encode.py runs as the script it is, and the directory function and its
# logP table are executed from the pinned source text.
#
#   python3 validation/fixtures/zinc22/gen_tranche_dirs.py > validation/fixtures/zinc22/tranche_dirs.tsv
#
# Tranches covered: every tranche in the maintainers' list of real 3D tranches (zinc22-2d
# all_3d_02_22_2023.txt), plus every logP bin at heavy-atom counts 0, 1, 29, 30 and 61 (the encodable
# extremes). The legacy pair (heavy atoms 0, logP bin 0 = `ZINC00...`) is excluded: the ZINC-22
# numbering defines it as "ZINC-20 and previous", which carries no tranche.
import ast
import os
import subprocess
import sys
import tempfile
import urllib.request

PINS = {
    "encode": "https://raw.githubusercontent.com/docking-org/cartblanche22/94dafee595e0f02b66b1a19cdf6d73ebf2693a11/encode.py",
    "build": "https://raw.githubusercontent.com/docking-org/zinc22-3d/7323bd4018c8f601c23ec4029858ce54eef0eb2e/generate/build_ligands.py",
    "tranches": "https://raw.githubusercontent.com/docking-org/zinc22-2d/cec4486014b9657d71e0778ab230b468ed57998d/utils-2d/tin/all_3d_02_22_2023.txt",
}
# Sub-ids cycled across tranches so the two hash levels (id characters 12-15) take varied values,
# including the smallest and the largest 10-character sub-id.
SUB_IDS = [1, 3843, 238327, 916132831, 4096000017, 839299365868340223]


def fetch(url):
    with urllib.request.urlopen(url) as r:
        return r.read().decode()


def directory_function(source):
    """The pinned `mp_range` table and `get_zinc_directory_hash`, executed from their source text."""
    tree = ast.parse(source)
    keep = [n for n in tree.body
            if (isinstance(n, ast.Assign) and any(getattr(t, "id", None) == "mp_range" for t in n.targets))
            or (isinstance(n, ast.FunctionDef) and n.name == "get_zinc_directory_hash")]
    env = {}
    exec(compile(ast.Module(body=keep, type_ignores=[]), "build_ligands.py", "exec"), env)
    return env["get_zinc_directory_hash"], env["mp_range"]


def main():
    get_dir, mp_range = directory_function(fetch(PINS["build"]))
    real = sorted({line.rstrip("/").split("/")[-1] for line in fetch(PINS["tranches"]).split() if line.strip()})
    synthetic = [f"H{h:02d}{b}" for h in (0, 1, 29, 30, 61) for b in mp_range if not (h == 0 and b == mp_range[0])]
    tranches = real + [t for t in synthetic if t not in set(real)]
    with tempfile.TemporaryDirectory() as tmp:
        enc = os.path.join(tmp, "encode.py")
        open(enc, "w").write(fetch(PINS["encode"]))
        print("# tranche\tsub_id\tzinc_id\tdirectory")
        print("# generated by validation/fixtures/zinc22/gen_tranche_dirs.py from:")
        for k, v in PINS.items():
            print(f"#   {k}: {v}")
        for i, tranche in enumerate(tranches):
            sub_id = SUB_IDS[i % len(SUB_IDS)]
            out = subprocess.run([sys.executable, enc, str(sub_id), tranche], capture_output=True, text=True, check=True)
            zinc_id = out.stdout.split()[-1]
            assert len(zinc_id) == 16, zinc_id
            print(f"{tranche}\t{sub_id}\t{zinc_id}\t{get_dir(zinc_id)}")


if __name__ == "__main__":
    main()
