//! ZINC-22 identifiers — today the one identifier scheme whose ids encode where a molecule is stored.
//!
//! An id is `ZINC` followed by 12 base-62 characters (`0-9a-zA-Z`): the heavy-atom count, the logP
//! bin (an index into the 61 bins below), then a 10-character sub-id (the maintainers' encoder,
//! docking-org/cartblanche22 `encode.py`, which asserts the 16-character length). Heavy-atom count and
//! logP both `0` mark an id from ZINC-20 or earlier, which carries no tranche (wiki.docking.org,
//! ZINC22:Numbering: "For backward compatibility, HAC and LogP are 0 for ZINC-20 and previous
//! versions"). The 3D database files an id under its tranche and two levels taken from the sub-id
//! (docking-org/zinc22-3d `generate/build_ligands.py` `get_zinc_directory_hash`).

const BASE62: &[u8; 62] = b"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";

/// The logP bins, indexed by the id's logP character (`logp_range` in the maintainers' encoder).
const LOGP_BINS: [&str; 61] = [
    "M500", "M400", "M300", "M200", "M100", "M000", "P000", "P010", "P020", "P030", "P040", "P050", "P060", "P070",
    "P080", "P090", "P100", "P110", "P120", "P130", "P140", "P150", "P160", "P170", "P180", "P190", "P200", "P210",
    "P220", "P230", "P240", "P250", "P260", "P270", "P280", "P290", "P300", "P310", "P320", "P330", "P340", "P350",
    "P360", "P370", "P380", "P390", "P400", "P410", "P420", "P430", "P440", "P450", "P460", "P470", "P480", "P490",
    "P500", "P600", "P700", "P800", "P900",
];

/// The 3D-database directory of a ZINC-22 id that carries a tranche:
/// `H{hac:02}/H{hac:02}{logP}/{id[12..14]}/{id[14..16]}`. `None` for every other string: anything that
/// is not `ZINC` + 12 base-62 characters, a logP character past the 61 bins, or a legacy id.
pub fn tranche_dir(id: &str) -> Option<String> {
    let rest = id.strip_prefix("ZINC")?.as_bytes();
    if rest.len() != 12 || !rest.iter().all(|b| BASE62.contains(b)) {
        return None;
    }
    let digit = |b: u8| BASE62.iter().position(|&d| d == b);
    let (hac, logp) = (digit(rest[0])?, digit(rest[1])?);
    if hac == 0 && logp == 0 {
        return None; // legacy id: no tranche
    }
    let tranche = format!("H{hac:02}{}", LOGP_BINS.get(logp)?);
    // `rest` is all ASCII, so these byte ranges are character ranges of the id
    Some(format!("{}/{tranche}/{}/{}", &tranche[..3], &id[12..14], &id[14..16]))
}

#[cfg(test)]
mod tests {
    use super::tranche_dir;

    /// Every record of the fixture generated by running the maintainers' encoder and directory function
    /// (validation/fixtures/zinc22/gen_tranche_dirs.py): each real 3D tranche and every logP bin at the
    /// heavy-atom extremes must land in the directory their code assigns.
    #[test]
    fn ids_go_where_the_maintainers_code_files_them() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../validation/fixtures/zinc22/tranche_dirs.tsv");
        let text = std::fs::read_to_string(&path).expect("fixture");
        let mut n = 0;
        for line in text.lines().filter(|l| !l.starts_with('#')) {
            let f: Vec<&str> = line.split('\t').collect();
            let (tranche, id, dir) = (f[0], f[2], f[3]);
            assert_eq!(tranche_dir(id).as_deref(), Some(dir), "{id} (tranche {tranche})");
            n += 1;
        }
        assert!(n > 1800, "fixture has {n} records");
    }

    /// Strings that are not ZINC-22 ids with a tranche have no directory. Expected values from the
    /// convention: 16 characters (the encoder's assertion), base-62 (its alphabet), 61 logP bins (its
    /// table), and HAC = logP = 0 meaning ZINC-20 and earlier (ZINC22:Numbering).
    #[test]
    fn everything_else_has_no_tranche_directory() {
        for id in [
            "ZINC000012345678",  // ZINC-15/20 style: HAC and logP 0, a legacy id
            "ZINC000000000001",  // the smallest legacy id
            "ZINC12345678",      // ZINC-12 style: too short
            "ZINC1Z0000000001",  // logP character `Z` is index 61, past the 61 bins
            "ZINC1h00000000012", // 17 characters
            "ZINC1h000000000",   // 15 characters
            "ZINC1h00000000_1",  // `_` is not base 62
            "ZINC1h0000000é1",   // non-ASCII, 16 bytes but not base 62
            "zinc1h0000000001",  // the prefix is case-sensitive
            "mc0001_n5_t2_ha41", // a macrocycle name
            "CSLB0000477NCT",
            "ZINC",
            "",
        ] {
            assert_eq!(tranche_dir(id), None, "{id:?}");
        }
    }
}
